name: Initiate and run microsoft sql server

on:
  push:
    branches:
      - "**"
env:
  VERSION: 1.0.0

jobs:
  initiate-and-run:
    name: Initiate
    runs-on: windows-latest

    steps:
      - name: Start SQL Server in Docker
        id: docker_start
        run: |
          docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=myTop!SecretSalmon1" --name "farmer" -p 1433:1433 -v farmerdata:/var/opt/mssql -d mcr.microsoft.com/mssql/server:2019-latest

      - name: Set up additional variables
        id: ga_env
        run: |
          echo "ENV_CONTAINER_ID=$(docker ps --all --filter status=running --no-trunc --format "{{.ID}}")" >> $GITHUB_ENV

      - name: Print variables
        run: |
          echo  "ENV_CONTAINER_ID: $ENV_CONTAINER_ID"
