name: Initiate and run microsoft sql server

on:
  push:
    branches:
      - "**"
env:
  VERSION: 1.0.0

jobs:
  initiate-and-run-mssql:
    name: Initiate
    runs-on: ubuntu-latest

    steps:
      - name: Start SQL Server in Docker
        id: docker_start
        run: |
          docker network create farmernet
          docker run --network farmernet --network-alias farmernetsql -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=myTop!SecretSalmon1" --name farmer -p 1433:1433 -v farmerdata:/var/opt/mssql -d mcr.microsoft.com/mssql/server:2019-latest

      - name: Set up additional variables
        id: ga_env
        run: |
          echo "ENV_CONTAINER_ID=$(docker ps --all --filter status=running --no-trunc --format "{{.ID}}")" >> $GITHUB_ENV

      - name: Print variables
        run: |
          echo  "ENV_CONTAINER_ID: $ENV_CONTAINER_ID"

  connect-to-mssql:
    name: Connect to database
    needs: initiate-and-run-mssql
    runs-on: windows-latest

    steps:
      - name: Print variables from new job
        shell: bash
        run: |
          docker network connect farmernet farmernetsql
          docker network inspect farmernet
          docker exec -it farmer "bash"
          /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'myTop!SecretSalmon1'
          select name from sys.databases
          go
          exit
          exit
